Automatically resize input images to match model
godly-devotion/MochiDiffusion pull request #341
Opened 2023-11-27 05:50 UTC by gdbing

fixes https://github.com/godly-devotion/MochiDiffusion/issues/205

## What
- resizes input images in img2img and ControlNet to match the model in generation pipeline
- adjusts aspect ratio of ImageWellView to show how the image will be cropped

## How
- input image dimensions are parsed from VAEEncoder.mlmodelc/metadata.json, stored as `inputSize` in SDModel
  - an early implementation I prototyped instantiated a `CoreML` `ManagedMLModel` object from the VAEEncoder.mlmodelc, to get the size, but it was too slow. Instead we directly open metadata.json and parse the size from that. This is fragile and inflexible, and will need to be updated if the model metadata ever changes, but it is more than 1000% faster
- `CGImage` extension method `scaledAndCroppedTo(size: CGSize)` is used to resize input images in generations
  - cropped to match required aspect ratio
    - so scaling won't squish or stretch image
  - crop is centred, e.g. crops equal amount off both edges
  - scaled to match required size
  - scales up or down
- applies to both img2img and ControlNet input images
- aspect ratio of ImageWellView matches the currently selected model so user can see how input image is being cropped
  - aspect ratio is square if current model doesn't support img2img (or if parsing the size from VAEEncoder.mlmodelc/metadata.json fails for any other reason)
  - image in ImageWellView is positioned in a fixed size frame so that it doesn't change size and move other controls around in the sidebar

## Images
### default square (e.g. 512x512)
<img width="234" alt="Screenshot 2023-11-25 at 9 24 31 PM" src="https://github.com/godly-devotion/MochiDiffusion/assets/8458547/7042f0f0-d920-41fc-911e-a205cc5d2be3">
<img width="234" alt="Screenshot 2023-11-25 at 9 24 29 PM" src="https://github.com/godly-devotion/MochiDiffusion/assets/8458547/aa206488-0132-4679-9640-22c7c564feeb">

### portrait (e.g. 512x768)
<img width="234" alt="Screenshot 2023-11-25 at 9 24 34 PM" src="https://github.com/godly-devotion/MochiDiffusion/assets/8458547/06d1e8a0-c181-49ab-81ce-8c176e3c0289">
<img width="234" alt="Screenshot 2023-11-25 at 9 24 25 PM" src="https://github.com/godly-devotion/MochiDiffusion/assets/8458547/dc1d47c3-95ba-40bb-9ff5-1182a1919cf8">

### Landscape (e.g. 768x512)
<img width="234" alt="Screenshot 2023-11-25 at 9 24 37 PM" src="https://github.com/godly-devotion/MochiDiffusion/assets/8458547/ede1580f-f6b6-40a8-8d0d-b5f5b0140d8e">
<img width="234" alt="Screenshot 2023-11-25 at 9 24 09 PM" src="https://github.com/godly-devotion/MochiDiffusion/assets/8458547/9881768b-b5ca-44dc-8d1f-b657c2be3e20">

(NB: ImageWellView can conform to any aspect ratio, these are just the common examples)

2023-11-27 06:07 UTC, gdbing commented
from https://github.com/godly-devotion/MochiDiffusion/issues/205:
> Ideally, it would have options to crop or stretch the image, and automatically infer the correct image size from the model being used

I didn't implement the stretch option.

I can't imagine ever using it and I think that adding the option is clutter.

I'm willing to be wrong though, if folks would like to add it, it wouldn't be difficult

2023-11-30 23:25 UTC, godly-devotion requested changes
Other than the minor comment, looks good!

2023-11-30 23:25 UTC, godly-devotion commented on Mochi Diffusion/Support/ImageController.swift
> +            if let name = controlNet.name, let size = currentModel?.inputSize, let image = controlNet.image?.scaledAndCroppedTo(size: size) {
Looks like `name = controlNet.name` is not being used and can be removed.

2023-12-01 21:47 UTC, godly-devotion commented on Mochi Diffusion/Support/ImageController.swift
> +            if let name = controlNet.name, let size = currentModel?.inputSize, let image = controlNet.image?.scaledAndCroppedTo(size: size) {
Looks like linter is complaining about creating an unused variable. Perhaps a guard would be more appropriate (and clearer about our intentions to check for `controlNet.name` existing).

2023-12-01 23:11 UTC, godly-devotion approved these changes

2023-12-01 23:12 UTC, merged